ToDoApp.MVC.UI/Models/EditToDoListModelView.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoApp.MVC.UI.Models
{
    public class EditToDoListModelView
    {
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

ToDoApp.MVC.UI/Models/ErrorViewModel.cs
namespace ToDoApp.MVC.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoApp.MVC.UI/Controllers/ApiBaseController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace ToDoApp.MVC.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class ApiBaseController : Controller
    {
        private IMediator? _mediator;
        public IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetRequiredService<IMediator>();
        protected IWebHostEnvironment _hostEnviroment
       => HttpContext.RequestServices.GetRequiredService<IWebHostEnvironment>();
    }
}

ToDoApp.MVC.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ToDoApp.MVC.UI.Models;

namespace ToDoApp.MVC.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoApp.MVC.UI/Controllers/ToDoItemController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Application.Commons.Models;
using ToDoApp.Application.UseCases.ToDoItems.Commands.CreateToDoItem;
using ToDoApp.Application.UseCases.ToDoItems.Commands.DeleteToDoItem;
using ToDoApp.Application.UseCases.ToDoItems.Commands.UpdateToDoItem;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetInformationAboutToDoItems;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItem;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItems;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItemsCompleted;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItemsInProgress;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItemsNotStarted;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItemsToday;
using ToDoApp.Application.UseCases.ToDoItems.Queries.GetToDoItemsWeek;
using ToDoApp.Application.UseCases.ToDoLists.Queries.GetToDoLists;
using ToDoApp.MVC.Controllers;

namespace ToDoApp.MVC.UI.Controllers
{
    public class ToDoItemController : ApiBaseController
    {
        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateToDoItem()
        {
            ToDoListDto[] toDoLists = await Mediator.Send(new GetToDoListsQuery());
            ViewData["ToDoLists"] = toDoLists;
            return View();
        }


        [HttpPost("[action]")]
        public async ValueTask<IActionResult> CreateToDoItem([FromForm] CreateToDoItemCommand toDoItem)
        {
            await Mediator.Send(toDoItem);
            return RedirectToAction("GetAllToDoItems");
        }



        [HttpGet("[action]")]
        public async ValueTask<IActionResult> ViewToDoItem(Guid id)
        {
            var toDoItem = await Mediator.Send(new GetToDoItemQuery(id));

            return View("ViewToDoItem", toDoItem);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> UpdateToDoItem(Guid Id)
        {
            var toDoItem = await Mediator.Send(new GetToDoItemQuery(Id));
            ToDoListDto[] toDoLists = await Mediator.Send(new GetToDoListsQuery());
            ViewData["ToDoLists"] = toDoLists;

            return View(toDoItem);
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> UpdateToDoItem([FromForm] UpdateToDoItemCommand ToDoItem)
        {
            await Mediator.Send(ToDoItem);
            return RedirectToAction("GetAllToDoItems");
        }


        public async ValueTask<IActionResult> DeleteToDoItem(Guid Id)
        {
            await Mediator.Send(new DeleteToDoItemCommand(Id));

            return RedirectToAction("GetAllToDoItems");
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoItems()
        {
            ToDoItemDto[] toDoItems = await Mediator.Send(new GetToDoItemsQuery());

            return View(toDoItems);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoItemsToday()
        {
            ToDoItemDto[] toDoItems = await Mediator.Send(new GetToDoItemsTodayQuery());

            return View(toDoItems);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoItemsWeek()
        {
            ToDoItemDto[] toDoItems = await Mediator.Send(new GetToDoItemsWeekQuery());

            return View(toDoItems);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoItemsCompleted()
        {
            ToDoItemDto[] toDoItems = await Mediator.Send(new GetToDoItemsCompletedQuery());

            return View(toDoItems);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoItemsInProgress()
        {
            ToDoItemDto[] toDoItems = await Mediator.Send(new GetToDoItemsInProgressQuery());

            return View(toDoItems);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoItemsNotStarted()
        {
            ToDoItemDto[] toDoItems = await Mediator.Send(new GetToDoItemsNotStartedQuery());

            return View(toDoItems);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllInforamtionRemider()
        {
            int[] information = await Mediator.Send(new GetInformationAboutToDoItemsQuery());

            return View(information);
        }
    }
}

ToDoApp.MVC.UI/Controllers/ToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Application.Commons.Models;
using ToDoApp.Application.UseCases.ToDoLists.Commands.CreateToDoList;
using ToDoApp.Application.UseCases.ToDoLists.Commands.DeleteToDoList;
using ToDoApp.Application.UseCases.ToDoLists.Commands.UpdateToDoList;
using ToDoApp.Application.UseCases.ToDoLists.Queries.GetToDoList;
using ToDoApp.Application.UseCases.ToDoLists.Queries.GetToDoLists;

namespace ToDoApp.MVC.Controllers
{
    public class ToDoListController : ApiBaseController
    {
        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateToDoList()
        {
            return View();
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> CreateToDoList([FromForm] CreateToDoListCommand ToDoList)
        {
            await Mediator.Send(ToDoList);

            return RedirectToAction("GetAllToDoLists");
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> UpdateToDoList(Guid Id)
        {
            var toDoList = await Mediator.Send(new GetToDoListQuery(Id));

            return View(toDoList);
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> UpdateToDoList([FromForm] UpdateToDoListCommand ToDoList)
        {
            await Mediator.Send(ToDoList);
            return RedirectToAction("GetAllToDoLists");
        }

        public async ValueTask<IActionResult> DeleteToDoList(Guid Id)
        {
            await Mediator.Send(new DeleteToDoListCommand(Id));

            return RedirectToAction("GetAllToDoLists");
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllToDoLists()
        {
            ToDoListDto[] toDoLists = await Mediator.Send(new GetToDoListsQuery());

            return View(toDoLists);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> ViewToDoList(Guid id)
        {
            var toDoList = await Mediator.Send(new GetToDoListQuery(id));

            return View("ViewToDoList", toDoList);
        }
    }
}

ToDoApp.MVC.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="display:flex; flex-direction:column; justify-content:center; align-items:center;">
    <h1 class="display-4" style="padding-top: 10px; font-weight:700">Welcome to ToDoApplication!</h1>

    <div class="d-flex align-items-center justify-content-center" id="main">
        <img src="/school.jpg" height="350px" />
    </div>

    <div class="button-container">
        <a asp-controller="ToDoList" asp-action="GetAllToDoLists" class="btn btn-primary">ToDoLists</a>
        <a asp-controller="ToDoItem" asp-action="GetAllToDoItems" class="btn btn-primary">ToDoItems</a>
        <a asp-controller="ToDoItem" asp-action="GetAllInforamtionRemider" class="btn btn-primary">Quick Reminder</a>
    </div>
</div>

<style>
    .button-container {
        margin-top: 20px;
    }
</style>

ToDoApp.MVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <title>@ViewData["Title"] - ToDoApp.MVC.UI</title>
    <style>
        /* Custom styles */
           .custom-sidebar {
        width: 200px; /* Adjust the width as needed */
    }
        .navbar-dark .navbar-nav .nav-link {
            color: white;
        }

            .navbar-dark .navbar-nav .nav-link:hover {
                color: yellow;
            }

        .sidebar .nav-link {
            color: white;
        }

            .sidebar .nav-link:hover {
                color: yellow;
            }

    </style>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="position:fixed;top:0; width:100%; z-index:1">
            <div class="container-fluid mx-4">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="ToDoList" asp-action="GetAllToDoLists" class="nav-link">ToDoList</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="ToDoItem" asp-action="GetAllToDoItems" class="nav-link">ToDoItem</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="ToDoItem" asp-action="GetAllInforamtionRemider" class="nav-link">Quick Reminder</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid" style="padding-top:50px; position:fixed">
        <div class="row">
            <aside class="bg-dark text-light col-2 sidebar" style="height: 100vh; width:125px">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsToday" class="nav-link">Today</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsWeek" class="nav-link">Week</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ToDoItem" asp-action="GetAllToDoItems" class="nav-link">All</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsCompleted" class="nav-link">Completed</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsInProgress" class="nav-link">InProgress</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsNotStarted" class="nav-link">NotStarted</a>
                    </li>
                </ul>
            </aside>
            
            <main class="col-10">
                <div class="container mt-3 pt-4" >
                    @RenderBody()
                </div>
            </main>

        </div>
    </div>

    <footer class="py-1 bg-dark mt-0" style="position: fixed; bottom:0; width:100%">
        <p class="text-center text-light pt-3">
            &copy; 2023 - ToDoApp.MVC.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-light">Privacy</a>
        </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoApp.MVC.UI/Views/ToDoItem/CreateToDoItem.cshtml
@using ToDoApp.Application.UseCases.ToDoItems.Commands.CreateToDoItem
@using ToDoApp.Application.UseCases.ToDoLists.Commands.CreateToDoList;
@using ToDoApp.Application.Commons.Models;
@using ToDoApp.Domain.States;

@{
    ViewData["Title"] = "CreateToDoItem";
    Layout = "_Layout";

    ToDoListDto[] ToDoLists = ViewData["ToDoLists"] as ToDoListDto[];
}

@model CreateToDoItemCommand

<h3>Create ToDo Item</h3>

<form asp-action="CreateToDoItem" method="post">
    <div class="form-group">
        <label asp-for="Title">Title:</label>
        <input asp-for="Title" class="form-control" required />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description">Description:</label>
        <input asp-for="Description" class="form-control" required />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Note">Note:</label>
        <input asp-for="Note" class="form-control" required />
        <span asp-validation-for="Note" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DueDate">DueDate:</label>
        <input asp-for="DueDate" type="date" class="form-control" required />
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ToDoItemStatus">Status:</label>
        <select asp-for="ToDoItemStatus" class="form-control" required>
            <option value="">Choose status</option>
            @foreach (var status in Enum.GetValues(typeof(ToDoItemStatus)))
            {
                <option value="@status">@status</option>
            }
        </select>
        <span asp-validation-for="ToDoItemStatus" class="text-danger"></span>
    </div>

    <div class="col-md-4">
        <label for="ToDoListId">ToDoList:</label>
        <select class="form-control" id="ToDoListId" name="ToDoListId" required>
            <option value="">Choose ToDoList</option>
            @foreach (var toDoList in ToDoLists)
            {
                <option value="@toDoList.Id">@toDoList.Name</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ToDoApp.MVC.UI/Views/ToDoItem/GetAllInforamtionRemider.cshtml
@{
    Layout = "_Layout";
}

@model int[]

<div class="text-center">

    <h1 class="display-4" style="font-weight: 500" >Hello you have @Model[0] tasks for today </h1>

    <div class="task-categories" style="padding-top:50px">
        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsToday" class="category-link">
            <span class="category-name">Today's Tasks:</span>
            <span class="task-count">@Model[0]</span>
        </a>

        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsWeek" class="category-link">
            <span class="category-name">Tasks for This Week:</span>
            <span class="task-count">@Model[1]</span>
        </a>

        <a asp-controller="ToDoItem" asp-action="GetAllToDoItems" class="category-link">
            <span class="category-name">All Tasks:</span>
            <span class="task-count">@Model[2]</span>
        </a>

        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsCompleted" class="category-link">
            <span class="category-name">Completed Tasks:</span>
            <span class="task-count">@Model[3]</span>
        </a>

        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsNotStarted" class="category-link">
            <span class="category-name">Not Started Tasks:</span>
            <span class="task-count">@Model[4]</span>
        </a>

        <a asp-controller="ToDoItem" asp-action="GetAllToDoItemsInProgress" class="category-link">
            <span class="category-name">In Progress Tasks:</span>
            <span class="task-count">@Model[5]</span>
        </a>
    </div>

</div>

<style>
    .category-link {
        display: block;
        padding: 10px;
        margin-bottom: 10px;
        background-color: #f0f0f0;
        border-radius: 5px;
        text-decoration: none;
        color: #333;
        transition: background-color 0.3s ease;
    }

        .category-link:hover {
            background-color: #e0e0e0;
        }

    .category-name {
        font-weight: bold;
        margin-right: 10px;
    }

    .task-count {
        font-weight: bold;
        color: #007bff;
    }
</style>

ToDoApp.MVC.UI/Views/ToDoItem/UpdateToDoItem.cshtml
@using ToDoApp.Application.UseCases.ToDoItems.Commands.UpdateToDoItem;
@using ToDoApp.Application.Commons.Models;
@using ToDoApp.Domain.Entities;
@using ToDoApp.Domain.States;
@model ToDoItemDto

@{
    ViewData["Title"] = "UpdateToDoItem";
    // Layout = "_Layout";
    ToDoListDto[] ToDoLists = ViewData["ToDoLists"] as ToDoListDto[];
}

<h1>Edit ToDoItem</h1>

<div class="form-container">
    <form asp-action="UpdateToDoItem" asp-controller="ToDoItem" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Title">Title:</label>
            <input asp-for="Title" class="form-control" required value="@Model.Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description">Description:</label>
            <input asp-for="Description" class="form-control" required value="@Model.Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Note">Note:</label>
            <input asp-for="Note" class="form-control" required value="@Model.Note" />
            <span asp-validation-for="Note" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="DueDate">Birth Date:</label>
            <input asp-for="DueDate" type="date" class="form-control" required value="@Model.DueDate.ToString("yyyy-MM-dd")" />
            <span asp-validation-for="DueDate" class="text-danger"></span>
        </div>

        <div class="col-md-4">
            <label for="ToDoListID">ToDoList:</label>
            <select class="form-control" id="ToDoListID" name="ToDoListID" required>
                <option value="">Choose ToDoList</option>
                @foreach (var toDoList in ToDoLists)
                {
                    <option value="@toDoList.Id">@toDoList.Name </option>
                }
            </select>
        </div>

        <div class="form-group">
            <label asp-for="ToDoItemStatus">Status:</label>
            <select asp-for="ToDoItemStatus" class="form-control" required>
                <option value="">Choose status</option>
                @foreach (var status in Enum.GetValues(typeof(ToDoItemStatus)))
                {
                    <option value="@status">@status</option>
                }
            </select>
            <span asp-validation-for="ToDoItemStatus" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ToDoApp.MVC.UI/Views/ToDoItem/ViewToDoItem.cshtml
@{
    Layout = "_Layout";
}

@model ToDoItemDto

<a asp-controller="Home" asp-action="index" class="btn btn-secondary back"><i class="las la-arrow-left"></i> Back to home</a>
<hr />


<div class="post-view">
    <div class="card mb-3" style="max-width: 940px;">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body m-3">
                    <p class="card-text">
                        @Model.Title
                        <div class="table-container">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 40%;">Title</th>
                                        <th style="width: 40%;">Description</th>
                                        <th style="width: 40%;">Note</th>
                                        <th style="width: 40%;">DueDate</th>
                                        <th style="width: 40%;">ItemStatus</th>
                                        <th style="width: 40%;">CreatedDate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td>@Model.Title</td>
                                            <td style="inline-size: 150px; overflow-wrap:break-word">@Model.Description</td>
                                            <td style="inline-size: 150px; overflow-wrap:break-word">@Model.Note</td>
                                            <td>@Model.DueDate</td>
                                            <td>@Model.ToDoItemStatus</td>
                                            <td>@Model.CreatedDate</td>
                                        </tr>
                                </tbody>
                            </table>
                        </div>
                        <div>
                            <div class="la-group">
                                <a asp-controller="ToDoItem" asp-action="UpdateToDoItem" asp-route-id="@Model.Id" class="btn btn-primary mx-2"><i class="las la-edit"></i>Edit</a>
                                <a asp-controller="ToDoItem" asp-action="DeleteToDoItem" asp-route-id="@Model.Id" onclick="return confirm('Are you sure delete this post?');" class="btn btn-danger mx-2"><i class="las la-trash"></i>Delete</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

ToDoApp.MVC.UI/Views/ToDoList/CreateToDoList.cshtml
@using ToDoApp.Application.UseCases.ToDoLists.Commands.CreateToDoList

@{
    ViewData["Title"] = "CreateToDoList";
    Layout = "_Layout";
}

@model CreateToDoListCommand

<h3 class="text-center">Add new ToDoList</h3>
<hr />

<form asp-controller="ToDoList" asp-action="CreateToDoList" enctype="multipart/form-data" method="post">
    <div class="container mt-3 custom-input">
        <label asp-for="Name" class="form-label">Name</label>
        <div class="input-group mb-3">
            <input asp-for="Name" type="text" class="form-control">
        </div>
        <span asp-validation-for="Name" class="text-danger"></span><br>
    </div>
    <div class="button-group">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>

ToDoApp.MVC.UI/Views/ToDoList/UpdateToDoList.cshtml
@using ToDoApp.Application.UseCases.ToDoLists.Commands.UpdateToDoList;
@using ToDoApp.Application.Commons.Models;
@using ToDoApp.Domain.Entities;
@model ToDoListDto

@{
    ViewData["Title"] = "UpdateToDoList";
    Layout = "_Layout";
}

<h3 class="text-center">Edit ToDoList</h3>
<hr />

<form asp-controller="ToDoList" asp-action="UpdateToDoList" enctype="multipart/form-data" method="post">
    <input type="hidden" asp-for="Id" />

       <div class="container mt-3 custom-input">
             <label asp-for="Name" class="form-label">ToDoList Name</label>
       <div class="input-group mb-3">
            <input asp-for="Name" type="text" class="form-control" value="@Model.Name">
       </div>
        <span asp-validation-for="Name" class="text-danger"></span><br>

        <div class="button-group">
            <button type="submit" class="btn btn-success">Save</button>
       </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ToDoApp.MVC.UI/Views/ToDoList/ViewToDoList.cshtml
@{
    Layout = "_Layout";
}

@model ToDoListDto

<a asp-controller="Home" asp-action="index" class="btn btn-secondary back"><i class="las la-arrow-left"></i> Back to home</a>
<hr />


<div class="post-view" style="overflow-y:hidden; overflow:auto; height:55vh; width:700px; margin-left:250px">
    <div class="card mb-3" style="max-width: 940px;">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body m-3">
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">
                        <div class="table-container">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 40%;">Title</th>
                                        <th style="width: 40%;">DueDate</th>
                                        <th style="width: 40%;">Status</th>
                                        <th style="width: 10%;">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var toDoItem in Model.ToDoItems)
                                    {
                                        <tr>
                                            <td>@toDoItem.Title</td>
                                            <td>@toDoItem.DueDate</td>
                                            <td>@toDoItem.ToDoItemStatus</td>
                                            <td class="action-links">
                                                <a href="@Url.Action("ViewToDoItem", "ToDoItem", new { id = toDoItem.Id })" class="btn btn-secondary">Details</a>
                                                <a href="@Url.Action("UpdateToDoItem","ToDoItem", new { id = toDoItem.Id })" class="btn btn-primary">Edit</a>
                                                <a href="@Url.Action("DeleteToDoItem", "ToDoItem", new { id = toDoItem.Id })" class="btn btn-danger">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div>
                            <div class="la-group">
                                <a asp-controller="ToDoList" asp-action="UpdateToDoList" asp-route-id="@Model.Id" class="btn btn-primary mx-2"><i class="las la-edit"></i>Edit</a>
                                <a asp-controller="ToDoList" asp-action="DeleteToDoList" asp-route-id="@Model.Id" onclick="return confirm('Are you sure delete this post?');" class="btn btn-danger mx-2"><i class="las la-trash"></i>Delete</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>